name: Java Build

on:
  push:
    branches:
      - main
permissions: write-all
jobs:

  build:
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'  
          distribution: 'adopt'
          cache: maven

      - name: Build REST API
        run: mvn package && exit 1
      - name: Send mail
        if: ${{ failure() }}
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
          body: ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
          to: adammielniczuk12@gmail.com
      - name: Upload REST API JAR artifact
        uses: actions/upload-artifact@v2
        with:
          name: rest-api-jar
          path: target/*.jar 
      

  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy JavaDoc 
        uses: MathieuSoysal/Javadoc-publisher.yml@v2.3.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          javadoc-branch: main
          java-version: '11'
          target-folder: javadoc 
  
