name: Java Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'  
          distribution: 'adopt'
          cache: maven

      - name: Build REST API
        run: mvn package 

      - name: Upload REST API JAR artifact
        uses: actions/upload-artifact@v2
        with:
          name: rest-api-jar
          path: target/*.jar 
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.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 }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload REST API JAR artifact
        uses: actions/upload-artifact@v2
        with:
          name: rest-api-jar
          path: target/*.jar
          target-path: ${{ github.workspace }}/dist

      - name: Attach artifact to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.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 }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/dist/*.jar
          asset_name: rest-api.jar
          asset_content_type: application/java-archive
